AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance for bitbucket app'
Parameters:
  InstanceType:
    Type: 'String'
    Description: 'Instance Type for the App Layer'
  InstanceTypenfs:
    Type: 'String'
    Description: 'Instance Type for the nfs' 
  SubnetId1: 
    Type: 'String'
    Description: 'default subnet id taken to check connectivity'
  PrivateIp1:
    Type: 'String'
    Description: 'Private IP address of the EC2 instance'
  PrivateIp2:
    Type: 'String'
    Description: 'Private IP address of the EC2 instance'  
  PrivateIp3:
    Type: 'String'
    Description: 'Private IP address of the EC2 instance'
  AvailabilityZone:
    Type: 'String'
    Description: 'Subnet Availability Zone'
  ImageId:
    Type: 'String'
    Description: 'AWS RHEL8  AMI'  
  ImageId2:
    Type: 'String'
    Description: 'AWS RHEL8  AMI' 
  RootVolumeSize:
    Type: 'String'
  DataVolumeSize:
    Type: 'String'
  nfsDataVolumeSize:
    Type: 'String' 
  KmsKeyId:
    Type: 'String'
    Description: 'KMS ID to encrypt EBS Volumes'
  KeyPairName:
    Type: 'String'
  bitec2instance1id:
    Type: 'String'
    Description: 'Exported bitbucket EC2 Instance Id for other stacks to use'
  bitec2instance2id:
    Type: 'String'
    Description: 'Exported bitbucket EC2 Instance Id for other stacks to use'
  bitnfsec2instanceid:
    Type: 'String'
    Description: 'Exported nfs EC2 Instance Id for other stacks to use'
  bitSecurityGroupId:
    Type: 'String'
    Description: Standard Security Group for bitbucket Access
  environmenttype:
    Type: 'String'
    Description: 'Application Environment' 
  osversion:
    Type: 'String'
    Description: 'Name of the operating system version'
  TagEnvironment:
    Type: 'String'
    Description: 'Environment variable for environment dev'
  itowner:
    Type: 'String'
    Description: 'Owner of the application'
  createdby:
    Type: 'String'
    Description: 'Name of the person who created this stack'
  applicationtier:
    Type: 'String'
    Description: 'Application type'
  costcenter:
    Type: 'Number'
    Description: 'CostCenter Number' 
  businessowner:
    Type: 'String'
    Description: 'Name of the Business unit'
  applicationname:
    Type: 'String'
    Description: 'Name of the application'

 
Resources:
  bitec2instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Ref: InstanceType
      ImageId: 
        Ref: ImageId
      
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp3"
          DeleteOnTermination: "true"
          Encrypted: "true"
          VolumeSize: !Ref RootVolumeSize
 
      # SubnetId:
      #   Ref: SubnetId1
      NetworkInterfaces:
      - NetworkInterfaceId:
          Ref: bitNetworkInterface1
        DeviceIndex: '0'
                 
      KeyName: !Ref KeyPairName
      
      Tags:
        - 
          Key: Name
          Value: !Join [ "-", ["aws", dv, "lx-bit01"]] # Value: "aws-pr-lx-art01"
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        - Key: os-version
          Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier
        
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo yum update -y           
            
  bitNetworkInterface1:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: 'bit Instance Primary interface with a static ip address'
      GroupSet:
        - 'Fn::ImportValue': !Sub "${bitSecurityGroupId}"
      SubnetId: !Ref SubnetId1
      SourceDestCheck: 'true'
      PrivateIpAddress: !Ref PrivateIp1
      
     
  bitEncryptedEBSVol1:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: "gp3"
      #DeleteOnTermination: "false"
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: "true"
      Size: !Ref DataVolumeSize
      KmsKeyId: !Ref KmsKeyId
      
  bitEncryptedEBSVol1Attachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref bitec2instance1
      VolumeId: !Ref bitEncryptedEBSVol1
      Device: /dev/sdc
###################################################
  bitec2instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Ref: InstanceType
      ImageId: 
        Ref: ImageId
      
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp3"
          DeleteOnTermination: "true"
          Encrypted: "true"
          VolumeSize: !Ref RootVolumeSize
 
      # SubnetId:
      #   Ref: SubnetId1
      NetworkInterfaces:
      - NetworkInterfaceId:
          Ref: bitNetworkInterface2
        DeviceIndex: '0'
                 
      KeyName: !Ref KeyPairName
      
      Tags:
        - 
          Key: Name
          Value: !Join [ "-", ["aws", dv, "lx-bit02"]] # Value: "aws-pr-lx-art01"
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        - Key: os-version
          Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier
        
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo yum update -y           
            
  bitNetworkInterface2:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: 'bit Instance Primary interface with a static ip address'
      GroupSet:
        - 'Fn::ImportValue': !Sub "${bitSecurityGroupId}"
      SubnetId: !Ref SubnetId1
      SourceDestCheck: 'true'
      PrivateIpAddress: !Ref PrivateIp2
      
     
  bitEncryptedEBSVol2:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: "gp3"
      #DeleteOnTermination: "false"
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: "true"
      Size: !Ref DataVolumeSize
      KmsKeyId: !Ref KmsKeyId
      
  bitEncryptedEBSVol2Attachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref bitec2instance2
      VolumeId: !Ref bitEncryptedEBSVol2
      Device: /dev/sdc

Outputs:
  bitec2instance1id: 
    Value:
      !Ref bitec2instance1
    Export:
      Name: !Ref bitec2instance1id

  bitec2instance2id: 
    Value:
      !Ref bitec2instance2
    Export:
      Name: !Ref bitec2instance2id
  
#   AppIPAddress:
#     Description: IP address of the newly created EC2 instance
#     Value: !Ref 'IPAddress'