AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application EC2 Instance'
Parameters:
  InstanceType:
    Type: 'String'
    Description: 'Instance Type for the App Layer'
  SubnetId1: 
    Type: 'String'
    Description: 'default subnet id taken to check connectivity'
  PrivateIp:
    Type: 'String'
    Description: 'Private IP address of the EC2 instance'
  AvailabilityZone:
    Type: 'String'
    Description: 'Subnet Availability Zone'
  ImageId:
    Type: 'String'
    Description: 'AWS RHEL8  AMI'  
  RootVolumeSize:
    Type: 'String'
  DataVolumeSize:
      Type: 'String'
  KmsKeyId:
    Type: 'String'
    Description: 'KMS ID to encrypt EBS Volumes'
  KeyPairName:
    Type: 'String'
  artec2instanceid:
    Type: 'String'
    Description: 'Exported EC2 Instance Id for other stacks to use'
  AppSecurityGroupId:
    Type: 'String'
    Description: Standard Security Group for App Access
  environmenttype:
    Type: 'String'
    Description: 'Application Environment' 
  osversion:
    Type: 'String'
    Description: 'Name of the operating system version'
  TagEnvironment:
    Type: 'String'
    Description: 'Environment variable for environment qa or prod'
  itowner:
    Type: 'String'
    Description: 'Owner of the application'
  createdby:
    Type: 'String'
    Description: 'Name of the person who created this stack'
  applicationtier:
    Type: 'String'
    Description: 'Application type'
  costcenter:
    Type: 'Number'
    Description: 'CostCenter Number' 
  businessowner:
    Type: 'String'
    Description: 'Name of the Business unit'
  applicationname:
    Type: 'String'
    Description: 'Name of the application'

 
Resources:
  artec2instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 
        Ref: InstanceType
      ImageId: 
        Ref: ImageId
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp3"
          DeleteOnTermination: "true"
          Encrypted: "true"
          VolumeSize: !Ref RootVolumeSize
 
      # SubnetId:
      #   Ref: SubnetId1
      NetworkInterfaces:
      - NetworkInterfaceId:
          Ref: artNetworkInterface
        DeviceIndex: '0'
                 
      KeyName: !Ref KeyPairName
      
      Tags:
        - 
          Key: name
          Value: !Join [ "-", ["aws", pr, "lx-art01"]] # Value: "aws-pr-lx-art01"
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        - Key: os-version
          Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier
        
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo yum update -y           
            
  artNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties: 
      Description: 'Art Instance Primary interface with a static ip address'
      GroupSet:
        - 'Fn::ImportValue': !Sub "${AppSecurityGroupId}"
      SubnetId: !Ref SubnetId1
      SourceDestCheck: 'true'
      PrivateIpAddress: !Ref PrivateIp
      #PrivateIpAddress: !Ref PrivateIp2
      Tags:
        -
          Key: name
          Value: !Join [ "-", ["aws", pr, "lx-art01"]]
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        - Key: os-version
          Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier

  artEncryptedEBSVol1:
    Type: AWS::EC2::Volume
    Properties:
      VolumeType: "gp3"
      #DeleteOnTermination: "false"
      AvailabilityZone: !Ref AvailabilityZone
      Encrypted: "true"
      Size: !Ref DataVolumeSize
      KmsKeyId: !Ref KmsKeyId
      Tags:
        -
          Key: name
          Value: !Join [ "-", ["aws", pr, "lx-art01"]]
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        - Key: os-version
          Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier

  artEncryptedEBSVol1Attachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref artec2instance
      VolumeId: !Ref artEncryptedEBSVol1
      Device: /dev/sdc

Outputs:
  artec2instanceid: 
    Value:
      !Ref artec2instance
    # Condition: Launch1
    Export:
      Name: !Ref artec2instanceid
  
#   AppIPAddress:
#     Description: IP address of the newly created EC2 instance
#     Value: !Ref 'IPAddress'