AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket for Artifactory application
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
  Environment:
    Type: String
    Description: The name of environment.
  TagEnvironment:
    Type: 'String'
    Description: 'Environment variable for environment dev or qa or prod'  
  
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
       BucketName: !Ref BucketName
       VersioningConfiguration:
         Status: Enabled
       BucketEncryption:
         ServerSideEncryptionConfiguration:
           - ServerSideEncryptionByDefault:
               SSEAlgorithm: 'aws:kms'
               KMSMasterKeyID: KMS-KEY-ARN
                 
Outputs:
  #BucketARN:
  #Description: 'The ARN of the bucket'
  #Value: !GetAtt ExampleBucket.Arn
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the Amazon S3 bucket.        
      