Parameters:
  VpcId:
    Type: 'String'
    Description: 'Vpc Id'
  #SSHPort:
  #  Type: 'String'
  #  Description: 'SSH remote login port'
  environmenttype:
    Type: 'String'
    Description: 'Application Environment'
  platform:
    Type: 'String'
    Description: 'Platform on which application runs' 
  applicationname:
    Type: 'String'
    Description: 'Name of the application'
  osversion:
    Type: 'String'
    Description: 'Name of the operating system version'
  createdby:
    Type: 'String'
    Description: 'Name of the person who created this stack'
  itowner:
    Type: 'String'
    Description: 'Owner of the application'
  costcenter:
    Type: 'Number'
    Description: 'CostCenter Number' 
  businessowner:
    Type: 'String'
    Description: 'Name of the Business unit'
  applicationtier:
    Type: 'String'
    Description: 'Name of the Application Architect'
  CtcSecurityGroupId:
    Type: 'String'
    Description: 'App Instance Security Group ID'   
  CtcpostgresSecurityGroupId:
    Type: 'String'
    Description: 'Postgres RDS Environment' 
Resources:
  CtcPostgresRDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ "-", ["use1-eas", !Ref environmenttype, "dvops-ctc-postgresRDS-sg"]] # 'Informatica_QA_Ora_SG'
      GroupDescription: 'Security group for CTC Postrges RDS DB instance'
      VpcId:
        Ref: VpcId
      Tags:
        - 
          Key: name
          Value: !Join [ "-", ["use1-eas", !Ref environmenttype, "dvops-ctc-postgresRDS-sg"]] #"Infor_QA_Ora_SG"    
        - Key: application-name
          Value: !Ref applicationname 
        - Key: environment-type
          Value: !Ref environmenttype
        # - Key: os-version
        #   Value: !Ref osversion 
        - Key: created-by
          Value: !Ref createdby          
        - Key: it-owner
          Value: !Ref itowner 
        - Key: cost-center
          Value: !Ref costcenter 
        - Key: business-owner
          Value: !Ref businessowner
        - Key: application-tier
          Value: !Ref applicationtier
  CtcPostgresSGIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: 'Security group inbound rule to allow traffic for Postgres RDS instances'
      GroupId: !Ref CtcPostgresRDSSG
      IpProtocol: tcp
      CidrIp: 172.16.0.0/12
      FromPort: 5432
      ToPort: 5432
      #SourceSecurityGroupId: !Ref CtcPostgresRDSSG
      
Outputs:
  CtcpostgresSecurityGroupId: 
    Value:
      !Ref CtcPostgresRDSSG
    Export:
      Name: !Ref CtcpostgresSecurityGroupId