template_path: artifactory-alb-sg.yaml
parameters:

  VpcId: vpc-09041cee364ae17b2
  environmenttype: prod
  tagenvironment: prod
  osversion: rhel-8
  artifactorylbSecurityGroupId: artifactorylbSecurityGroupId
  platform: devops
  applicationname: artifactory
  createdby: bollur@shure.com
  itowner: khany@shure.com
  costcenter: "1505"
  businessowner: komosar@shure.com
  applicationtier: application
         
    
